apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  labels:
    run: go-hello-world
  name: go-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: go-hello-world
    spec:
      containers:
      - image: gcr.io/personal-195700/go-hello-world:3e5b60934769c1349f17a8acd79c6daa2cc381f0
        imagePullPolicy: IfNotPresent
        name: go-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
