apiVersion: v1
kind: Service
metadata:
  labels:
    run: go-hello-world
  name: go-hello-world
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: go-hello-world
  sessionAffinity: None
  type: LoadBalancer

